### ISSUE TITLE
Disable Autogrow in Given-When-Then Template

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/VITAC-NIDays-Demo#1]
autogrow is awful

**Comment by joerghampel** [comment]
How do I claim it?

**Comment by joerghampel** [comment]
on which VI?

**Comment by JamesMc86** [comment]
The Given When Then.vi in the Templates folder - the sequence structure there has autogrow enabled still

**Comment by JamesMc86** [comment]
Merged the PR
